name: flutter_cohere
description: "Flutter Cohere SDK. Cohere empowers every developer and enterprise to build amazing products and capture true business value with language AI."
version: 0.0.2

repository: https://github.com/abdibrokhim/flutter_cohere
issue_tracker: https://github.com/abdibrokhim/flutter_cohere/issues

topics:
  - cohere
  - ai
  - flutter-cohere

platforms:
  android:
  ios:
  web:
  linux:
  windows:
  macos:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  json_annotation: ^4.8.1
  test: ^1.24.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
